# Generated by Django 4.1.7 on 2023-02-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
                ('descr', models.TextField()),
            ],
        ),
    ]
